version: '3.8'

services:
  graphql:
    build: .
    container_name: graphql-app
    expose:
      - "4000"
    networks:
      - app-network

  nginx:
    image: nginx:latest
    container_name: graphql-nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - graphql
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
